ekf_filter_node:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    two_d_mode: true
    frequency: 30.0
    sensor_timeout: 0.1
    publish_tf: false
    print_diagnostics: true

    odom0: /diff_cont/odom            # wheel odom
    odom0_queue_size: 5
    odom0_differential: false
    odom0_relative: false
    odom0_config: [true,true,false,  false,false,true,
                   true,true,false,  false,false,true,
                   false,false,false]

    imu0: /imu/data   # Madgwick (pure IMU)
    imu0_queue_size: 10
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    # roll/pitch orientation + gyro rates; (skip yaw orientation, no mag)
    imu0_config: [false,false,false,  false,false,false,
                  false,false,false,  true,true,true,
                  true,true,true]
