mpu6050driver:
  ros__parameters:
    gyro_range: 0
    accel_range: 0
    dlpf_bandwidth: 1        # try 2–3; lower = smoother
    frequency: 50        # integer, not 100.0
    # After measuring (see below), put your averages here:
    gyro_x_offset: 0.00      # deg/s
    gyro_y_offset: 0.00
    gyro_z_offset: 0.00
    accel_x_offset: 0.00     # m/s^2
    accel_y_offset: 0.00
    accel_z_offset: 0.00
